package com.usedcarrot.audit.domain;

public enum AuditEventType {
    REGISTER,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    PASSWORD_CHANGED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    PRODUCT_STATUS_CHANGED,
    MESSAGE_SENT,
    WALLET_CREATED,
    WALLET_INITIAL_GRANTED,
    WALLET_ADMIN_GRANTED,
    CARROTCOIN_TRANSFER_COMPLETED,
    CARROTCOIN_TRANSFER_FAILED,
    REPORT_CREATED,
    REPORT_PROCESSED,
    USER_STATUS_CHANGED,
    ACCESS_DENIED,
    FILE_UPLOAD_REJECTED
}
